feat(01-building-blocks): added workflor file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -11,5 +11,9 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-    - name: Failed steps
-      run: echo "Goodbye!"
+        - name: Failed step
+          run: |
+            echo "I will fail"
+            exit 1
+        - name: Say goodbye
+          run: echo "Goodbye!"
